export {
  buildAuthRedirectAllowList,
  CANONICAL_PRODUCTION_HOST,
  CANONICAL_PRODUCTION_ORIGIN,
  DEFAULT_AUTH_REDIRECT_ORIGINS,
  VERCEL_PRODUCTION_HOST,
  VERCEL_PRODUCTION_ORIGIN
} from "@/lib/site-url";
